spring.application.name=partnersAPI

# Define cores no terminal
spring.output.ansi.enabled=always

# Define path raiz do endpoint
# http://localhost:8080/airports/algumacoisa
server.servlet.context-path=/partners

spring.profiles.active=test
#spring.profiles.active=prod


# Defini\u00e7\u00e3o de Porta
# Procura uma variavel de ambiente SERVER_PORT. Caso n\u00e3o exista utiliza
# a porta 8080 como default.

# server.port=${SERVER_PORT:8080}
